// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3Fq7L3fkFa415rKVgpDGwfmHTXbh264',
    appId: '1:617141485794:web:9cab9fe5721ad01a281ebb',
    messagingSenderId: '617141485794',
    projectId: 'starsync-9d24c',
    authDomain: 'starsync-9d24c.firebaseapp.com',
    storageBucket: 'starsync-9d24c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTy1qdLIijmLzYy9xt8jwqmhEisSWjohI',
    appId: '1:617141485794:android:3330848fca7b311a281ebb',
    messagingSenderId: '617141485794',
    projectId: 'starsync-9d24c',
    storageBucket: 'starsync-9d24c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzNFNZbQW62-bFB6heP2FhSrUT_OCgjAc',
    appId: '1:617141485794:ios:558766ab4e4ceadb281ebb',
    messagingSenderId: '617141485794',
    projectId: 'starsync-9d24c',
    storageBucket: 'starsync-9d24c.appspot.com',
    iosBundleId: 'com.example.starsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzNFNZbQW62-bFB6heP2FhSrUT_OCgjAc',
    appId: '1:617141485794:ios:726351260fe8142a281ebb',
    messagingSenderId: '617141485794',
    projectId: 'starsync-9d24c',
    storageBucket: 'starsync-9d24c.appspot.com',
    iosBundleId: 'com.example.starsync.RunnerTests',
  );
}
